language: python
dist: xenial
python: 3.7
before_install:
    - sudo apt update
    - sudo apt -y install rabbitmq-server
install:
    - pip install -r requirements.txt
    - python3 -c "import nltk; nltk.download('punkt')"
services:
    - mongodb
script:
    - cp secure/db.json.example secure/db.json
    - cp secure/celery.json.example secure/celery.json
    - celery worker -A app.celery &
    - python3 -m pytest tests
