language: python
dist: xenial
python: 3.7
addons:
  apt:
    packages:
      - rabbitmq-server
install:
    - pip install -r requirements.txt
    - python3 -c "import nltk; nltk.download('punkt')"
services:
    - mongodb
script:
    - cp secure/celery.json.example secure/celery.json
    - celery worker -A app.celery &
    - python3 -m pytest tests
