language: python
dist: trusty
python: 3.6
install:
    - pip install -r requirements.txt
    - python3 -c "import nltk; nltk.download('punkt')"
services:
    - mongodb
    - rabbitmq
script:
    - cp secure/celery.json.example secure/celery.json
    - celery worker -A app.celery &
    - python3 -m pytest tests
