language: python
dist: xenial
python: 3.7
install:
    - pip install -r requirements.txt
    - python3 -c "import nltk; nltk.download()"
services:
    - mongodb
script:
    - cp secure/celery.json.example secure/celery.json
    - python3 -m pytest tests
